@startuml
skin rose
skinparam ActivityFontSize 12
skinparam ArrowFontSize 12
start
:User executes AddCommand;
:AddCommandParser parses user input;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([input is valid])
    :Construct Company object;
    :Construct AddCommand object;
    :Return back to LogicManager;
    :LogicManager executes AddCommand;
    if () then ([company already exists])
        :Display duplicate company error message;
    else ([else])
        :Insert company to CompanyList;
        :Update UI;
    endif

else ([else])
:Display error message;

endif
stop
@enduml
