@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1

participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "c:Company" as Company MODEL_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR

end box

box Model MODEL_COLOR_T1
participant "m:ModelManager" as Model MODEL_COLOR
end box

[-> LogicManager : execute("add c/Google \n r/Software Engineer s/PA \n d/10-10-2023 n/Francis Tan \n p/98765432 e/francist@gmail.com")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("add c/Google \n r/Software Engineer s/PA \n d/10-10-2023 n/Francis Tan \n p/98765432 e/francist@gmail.com")
activate AddressBookParser

create AddCommandParser
AddressBookParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> AddressBookParser
deactivate AddCommandParser

AddressBookParser -> AddCommandParser : parse("c/Google \n r/Software Engineer s/PA \n d/10-10-2023 n/Francis Tan \n p/98765432 e/francist@gmail.com")
activate AddCommandParser

create Company
AddCommandParser -> Company: Company(...)
activate Company

Company --> AddCommandParser
deactivate Company

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser : a
deactivate AddCommand


AddCommandParser --> AddressBookParser : a
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> AddressBookParser
destroy AddCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddCommand : execute(m)
activate AddCommand

AddCommand -> Model : hasCompany(c)
activate Model

Model --> AddCommand
deactivate Model

AddCommand -> Model : addCompany(c)
activate Model

Model --> AddCommand
deactivate Model

AddCommand -> Model : setCurrentViewedCompany(c)
activate Model

Model --> AddCommand
deactivate Model

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand
deactivate CommandResult

AddCommand --> LogicManager
deactivate AddCommand

[<--LogicManager
deactivate LogicManager

@enduml
